{% set name = "pymatgen-io-validation" %}
{% set version = "0.1.4" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/pymatgen_io_validation-{{ version }}.tar.gz
  sha256: b3f29de9ac30a8d12afba8d9b8882a6bbbaa21175a93644afb4c55a303b17369

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=65.0.0
    - versioningit >=1,<4
    - wheel
    - pip
  run:
    - pymatgen-core >=2026.4.16
    - python >={{ python_min }}
    - pymatgen
    - numpy
    - requests
    - pydantic >=2.0.1
    - pydantic-settings >=2.0.0

test:
  imports:
    - pymatgen.io.validation
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/materialsproject/pymatgen-io-validation
  summary: A comprehensive I/O validator for electronic structure calculations
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
